-- +goose Up
CREATE TABLE If NOT EXISTS carts (
    id BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS cart_items (
    id BIGSERIAL PRIMARY KEY,
    cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    product VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL
);

-- +goose Down
DROP TABLE IF EXISTS carts;
DROP TABLE IF EXISTS cart_items;