apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-api-deployment
  labels:
    app: cart-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres-service 5432;
              do
                echo "Waiting db connection"
                sleep 2;
              done;
      containers:
        - name: cart-api
          image: cart-api:latest
          imagePullPolicy: Never
          ports: 
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: config-volume
          configMap:
            name: cart-api-config
            items: 
              - key: config.yaml
                path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api-service
spec:
  selector:
    app: cart-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP   