// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "cart-api/internal/entity"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// AddCartItem provides a mock function with given fields: ctx, cartID, item
func (_m *Repository) AddCartItem(ctx context.Context, cartID int64, item entity.AddCartItemRequest) (entity.CartItem, error) {
	ret := _m.Called(ctx, cartID, item)

	if len(ret) == 0 {
		panic("no return value specified for AddCartItem")
	}

	var r0 entity.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.AddCartItemRequest) (entity.CartItem, error)); ok {
		return rf(ctx, cartID, item)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.AddCartItemRequest) entity.CartItem); ok {
		r0 = rf(ctx, cartID, item)
	} else {
		r0 = ret.Get(0).(entity.CartItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, entity.AddCartItemRequest) error); ok {
		r1 = rf(ctx, cartID, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCart provides a mock function with given fields: ctx
func (_m *Repository) CreateCart(ctx context.Context) (entity.Cart, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateCart")
	}

	var r0 entity.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (entity.Cart, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) entity.Cart); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(entity.Cart)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveCartItem provides a mock function with given fields: ctx, cartID, itemID
func (_m *Repository) RemoveCartItem(ctx context.Context, cartID int64, itemID int64) error {
	ret := _m.Called(ctx, cartID, itemID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveCartItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, cartID, itemID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ViewCart provides a mock function with given fields: ctx, cartID
func (_m *Repository) ViewCart(ctx context.Context, cartID int64) (entity.Cart, error) {
	ret := _m.Called(ctx, cartID)

	if len(ret) == 0 {
		panic("no return value specified for ViewCart")
	}

	var r0 entity.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (entity.Cart, error)); ok {
		return rf(ctx, cartID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) entity.Cart); ok {
		r0 = rf(ctx, cartID)
	} else {
		r0 = ret.Get(0).(entity.Cart)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, cartID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
