apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: postgres-deployment
  namespace: {{ .Values.environment }}
  labels:
    app: postgres
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
   matchLabels:
    app: postgres
  template:
    metadata:
      labels:
       app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: cart-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cart-db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: cart-api-config
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.auth.user | quote }}, "-d", {{ .Values.postgres.auth.database | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
             command: ["pg_isready", "-U", {{ .Values.postgres.auth.user | quote }}, "-d", {{ .Values.postgres.auth.database | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}