apiVersion: v1
kind: Secret
metadata:
  name: cart-db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}